# Generated by Django 4.2.3 on 2023-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_alunos_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cpf',
            field=models.BigIntegerField(verbose_name='CPF'),
        ),
    ]
